### PR TITLE
feat: Add dist-tag for preview publishing... and fix the published boolean bug

### LINKED ISSUE #197: The published boolean is never set or toggled
See source [here](https://github.com/jbolda/covector/blob/main/packages/action/src/index.ts#L80-L87).

The output `packagesPublished` will always return an empty string because `covectored[pkg].published` boolean is never set. I believe this is something that needs to be triggered inside [`attemptCommands`](https://github.com/jbolda/covector/blob/main/packages/command/index.ts#L22-L137) once it detects that a `publish` command has been executed.

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
To add tags to the preview packages. It's fine as is at the moment because the pre-release semver syntax _without_ bumping means the latest tag will not be compromised but it's still nice to tag the preview packages for NPM.

## Approach
- `action.command.preview` will now pass in `covector({ ..., branchTag })`
  - the branchTag takes the branch name from the context of the workflow
    - the branch is then converted in the same manner our current preview action treats its tags:
      ```js
      const branchTag = branchName.replace(/(?!.\_)\_/g, '__').replace(/\//g, '_');
      ```
- ~the `branchTag` argument gets utilized _within_ `covector`'s preview command by mutating the publish commands~
  - ~alternatively I could've passed in the branchTag into `mergeIntoConfig` but there's a lot going on in there and mutating the object after `mergeIntoConfig` seemed to provide more clarity~
  - ~see TODO below but the tagging only works if the publish command is a single command and therefore shouldn't be an array~
- the `branchTag` variable is exposed through piping into the template so users can configure their command like this:
```js
{
  "publish": "npm publish ${ pkg.tag ? '--tag pkg.tag' : '' }"
}
```
- fixed the published boolean bug. resolves #197

## TODOs
- [x] Prevent `latest`
  - [x] ⚠️ I configured the action to throw an error if the branch name of a pull request is `latest` but this only applies to the `preview` command in action. Should this be brought up higher to include pre-release publishing?
- [x] ⚠️ ~The publish command can be an array in which case it is difficult to auto-detect which command we should be slapping on the tag argument. But since we have pre-publish and post-publish, would it be possible to restrict the publish command to be a single string property?~
- [x] ⚠️ ~The `--tag TagName` works for NPM but I'm not sure about other registries~
- [x] ⚠️ ~Write tests for action package~ On second thought, maybe we don't need to write tests for the action because all it does is receive arguments and pass it into covector. So I think we can cover the test cases from covector's end?
- [x] ~~Oops, forgot to take out an `only` flag in one of the test suites from a previous PR~~ Fixed
- [x] I have the `published` boolean toggled at the end of `attemptCommands` for when `_pkgCommandsRan` exists, command is `publish` and there are no `commandPrefixes`.
- [x] Add change files once the other TODOs are sorted

### CODE REVIEW

File: __fixtures__/integration.js-and-rust-for-preview/.changes/config.json [hunk 1]
```diff
@@ -2,11 +2,15 @@
   "pkgManagers": {
     "javascript": {
       "version": true,
-      "publish": "echo publishing ${ pkg.pkg } would happen here"
+      "publish": "echo publishing ${ pkg.tag ? '--tag pkg.tag' : '' } would happen here",
```
Comment (jbolda) [inline __fixtures__/integration.js-and-rust-for-preview/.changes/config.json:5]: `'--tag pkg.tag'` appears to only return a string. I think we want something like `'--tag ' + pkg.tag`. Same below.

Not a big deal, but there is an extra space if the template returns `''`.

**Review by jbolda — APPROVED** [review]
Looks good! A bit of a nit, but it would be nice to have the value in our snapshot. Then we are good to go. Feel free to merge after you have updated this.

File: __fixtures__/integration.js-and-rust-for-preview/.changes/config.json (hunk 1 above)
Comment (minkimcello) [reply __fixtures__/integration.js-and-rust-for-preview/.changes/config.json]: Ah I see. I fixed the fixture and getting the results we want:

```js
"javascript": {
  "publish": "echo publishing${ !pkg.tag ? ' --tag ' + pkg.tag : null } would happen here",
},
```
